name: Capital Formation in the 21st Century
favicon: null
layout_spectrum: 0.15635
typography_spectrum: 0.84726
title: Capital Formation in the 21st Century
cta:
  domain: null
  bucket: null
  version: null
analytics:
  google: null
  facebook: null
  twitter: null
opengraph:
  image: null
  type: null
  appId: null
color:
  brandColors:
    - '#ffffff'
    - '#0073da'
    - '#92c5f0'
    - '#fbacab'
    - '#f85553'
  brandStrength: 0.19080359768122435
  lightness: 0.1759946788661182
  saturation: 0.9649478669743985
  rhythmicContrast: 0.8319122691173106
purpose: []
