name: capital
favicon: null
layout_spectrum: 0.9524328985717148
typography_spectrum: 0.4577400959096849
cta:
  domain: null
  bucket: null
  version: null
analytics:
  google: null
  facebook: null
  twitter: null
opengraph:
  image: null
  type: null
  appId: null
color:
  brandColors:
    - '#17BEBB'
    - '#2E282A'
    - '#CD5334'
    - '#EDB88B'
    - '#FAD8D6'
  brandStrength: 0.19080359768122435
  lightness: 0.1759946788661182
  saturation: 0.9649478669743985
  rhythmicContrast: 0.8319122691173106
purpose: []
