name: Capital
favicon: null
layout_spectrum: 0.15635
typography_spectrum: 0.84726
style: the-composer
title: Capital Formation in the 21st Century
cta:
  domain: null
  bucket: null
  version: null
analytics:
  google: null
  facebook: null
  twitter: null
opengraph:
  image: null
  type: null
  appId: null
color:
  brandColors:
    - '#B0CC99'
    - '#677E52'
    - '#B7CA79'
    - '#F6E8B1'
    - '#89725B'
  brandStrength: 0.6249297140166163
  lightness: 0.6296718579251319
  saturation: 0.10741267562843859
  rhythmicContrast: 0.7145364028401673
purpose: []
