name: Capital
favicon: null
layout_spectrum: 0.15635
typography_spectrum: 0.84726
title: Capital Formation in the 21st Century
cta:
  domain: null
  bucket: null
  version: null
analytics:
  google: null
  facebook: null
  twitter: null
opengraph:
  image: null
  type: null
  appId: null
color:
  brandColors:
    - '#e5e8cb'
    - '#2c4947'
    - '#709f8f'
    - '#b8aa8f'
    - '#b68b58'
  brandStrength: 1
  lightness: 0.875
  saturation: 0.5625
  rhythmicContrast: 0.8319122691173106
purpose: []
